### ISSUE TITLE
Server Side Rendering Error: TypeError: _createApp is not a function (Docker)

### ISSUE THREAD

**Issue by SirMishaa** [nuxt/framework#1012]
### Environment

Nuxt CLI v3.0.0-27235989.d52b1e8                                                                                         08:57:36
RootDir: /app                                                                                                            08:57:37
Nuxt project info:                                                                                                       08:57:37

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.10.0`
- Nuxt Version:     `3-3.0.0-27235989.d52b1e8`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

Hello

I've set up a new project using "npx nuxi init nuxt3-app" and made a basic Dockerfile and docker-compose.yaml

When I start the project using docker-compose up (which execute ``yarn run dev``, I got an error : 
> Server Side Rendering Error: TypeError: _createApp is not a function
2021-10-14T08:56:10.602075756Z     at renderToString (file:///app/node_modules/vue-bundle-renderer/dist/index.mjs:248:25)
2021-10-14T08:56:10.602080926Z     at async renderMiddleware (file:///app/.nuxt/nitro/index.mjs:166:20)
2021-10-14T08:56:10.602083436Z     at async handle (file:///app/node_modules/h3/dist/index.mjs:571:19)
2021-10-14T08:56:10.764373732Z Server Side Rendering Error: TypeError: _createApp is not a function
2021-10-14T08:56:10.764408293Z     at renderToString (file:///app/node_modules/vue-bundle-renderer/dist/index.mjs:248:25)
2021-10-14T08:56:10.764412273Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-10-14T08:56:10.764414893Z     at async renderMiddleware (file:///app/.nuxt/nitro/index.mjs:166:20)
2021-10-14T08:56:10.764416863Z     at async handle (file:///app/node_modules/h3/dist/index.mjs:571:19)

### Reproduction

See this basic repo
https://github.com/SirMishaa/nuxt3-poc

### Additional context
Dockerfile :
```Dockerfile
FROM node:16-alpine3.14

WORKDIR app

COPY package.json .

RUN yarn install

COPY . .

EXPOSE 3000
CMD ["yarn", "run", "dev"]

```

docker-compose.yaml : 
```yaml
version: "3.0"

services:
  node:
    build:
      context: . # Using context "current folder of docker-compose" cause Dockerfile is in the @/docker folder
      dockerfile: docker/Dockerfile
    ports:
      - "3005:3000"
    volumes:
      - ./:/app
```
