### ISSUE TITLE
src: url("assets/fonts/my-font.ttf") rewritten to '__NUXT_BASE__/my-font.ttf' in production build

### ISSUE THREAD

**Issue by sewalsh** [nuxt/framework#2777]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.3.1`
- Nuxt Version:     `3.0.0-27375427.d07d572`
- Package Manager:  `yarn@3.2.0-rc.10`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `privateRuntimeConfig`, `buildModules`, `css`, `vite`, `unocss`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@7.5.3`, `unplugin-icons/nuxt`, `@unocss/nuxt@0.22.4`
------------------------------

### Reproduction

...

### Describe the bug

I suspect this may be related to #2655. 

It only affects `yarn build`.

``` css
@font-face {
    font-family: "SpaceGroteskLight";
    src: url("assets/fonts/SpaceGrotesk-Light.ttf");
    font-display: swap;
}
```
