### ISSUE TITLE
corrupted and missing assets in built vite app ('Failed to decode downloaded font')

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#2888]
> Have same issue ![image](https://user-images.githubusercontent.com/28978908/150323842-6f771abb-0a57-41c3-983b-5e1ef9542127.png)

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27383920.81ee59c`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

The last release 3.0.0-27383920.81ee59c fixed the problem with images in /assets loaded from css url() now loaded correctly, but remains an issue with fonts loaded from /assets in css @font-face, i attach a screenshot of it: (Failed to decode downloaded font: / Failed to load response data)

Fonts loaded as: 
```css
/* assets/css/fonts.css */
@font-face {
  font-family: 'Noto-Sans';
  src: url('assets/fonts/noto-sans/NotoSans-Regular.ttf') format('truetype');
}
```

<img width="924" alt="failed-to-decode-font" src="https://user-images.githubusercontent.com/13294791/150819597-8abf07e5-bab1-4593-b45a-5d0b0af8dc0b.png">

_Originally posted by @arb85 in https://github.com/nuxt/framework/issues/2777#issuecomment-1020264094_
