### ISSUE TITLE
Not creating dist folder on nuxt3 project using github actions. 

### ISSUE THREAD

**Issue by anburocky3** [nuxt/framework#4439]
### Describe the bug

While fetching the data from the github repo, it is working good, but if i make my own github action with all required information, it is not building nuxt3 `dist` folder.

As per nuxt3 netlify docs: https://v3.nuxtjs.org/guide/deployment/netlify

It is not detecting the netlify environment while building.

### Steps to reproduce

1. Run `git clone https://github.com/anburocky3/iragugal-web`
2. Check the github actions: `.github/workflows/netlify.yaml` & `netlify.toml` file
3. Try to push it and the action fails with this error message.

![image](https://user-images.githubusercontent.com/15264938/164088932-590406ed-a7eb-47fd-a39a-d27fdb413343.png)

### Configuration

```toml
[dev]
  command = "sleep 999999999"
  framework = "#custom"
  functions = ".output/server"
  port = 8888
  targetPort = 3000

[build]
  command = "yarn build"
  publish = "dist/"
  functions = ".output/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
```

### Environment

```properties
  System:
    OS: Windows 10 10.0.22598
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 20.23 GB / 31.92 GB
  Binaries:
    Node: 16.14.2 - S:\laragon\bin\nodejs\node-v16.14.2-win-x64\node.EXE
    Yarn: 3.2.0 - S:\laragon\bin\nodejs\node-v16.14.2-win-x64\yarn.CMD
    npm: 8.5.0 - S:\laragon\bin\nodejs\node-v16.14.2-win-x64\npm.CMD
  npmPackages:
    netlify-cli: ^10.0.0 => 10.0.0
```

Have created this issue with `nitro-deploys`: https://github.com/unjs/nitro-deploys/issues/9 (Feel free to close, if it is repetative)
