### ISSUE TITLE
Cloudflare - Public directory return 404 on some file types

### ISSUE THREAD

**Issue by chakflying** [nuxt/framework#4525]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v17.7.1`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.2`
- Builder:          `vite`
- User Config:      `buildModules`, `build`, `css`, `postcss`, `dir`, `head`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.3`

### Reproduction

1. add various file types to the `/public` directory
2. in `nuxt.config.ts`, add 
```js
  nitro: {
    preset: 'cloudflare',
  }
```
4. deploy to cloudflare with `wrangler publish`
5. observe some files return 404

### Describe the bug

I tested these files:
- .txt: work
- .jpg: work
- .docx: 404
- .pdf: 404

### Additional context

`wrangler.toml`:

```toml

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "npm run build"
upload.format = "service-worker"
```

I tested with `miniflare` and 404 is also displayed.
