### ISSUE TITLE
CSS not minified when using Font Awesome Icons

### ISSUE THREAD

**Issue by jasonlundien** [nuxt/framework#5231]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.3.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.2`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

A reproduction and small [project](https://github.com/jasonlundien/fa-nuxt-3-example)

### Describe the bug

With Nuxt2, the css and minification was handled by setting `config.autoAddCss = false`.
When `npm run build` was ran, a `.js` file was generated under the `dist/_nuxt/` directory which included the minified Font Awesome css classes, etc.

With Nuxt3, the minification seems to be handled a bit differently... yet I cannot figure out how to get the Font Awesome css classes to be minified upon an `npm run build` even with setting `config.autoAddCss = false`.  An unminified version of the classes is written in the `.nuxt/dist/client/` directory in a `.mjs` directory.  No warnings, errors, etc.

In both versions you can search for `.svg-inline--fa` and see the minified in Nuxt2 and the unminified in Nuxt3.

### Additional context
Additionally, I have tried to adjust `minifyCSS` and `minifyJS` manually by adding the following to `nuxt.config.ts`, but this did not work either, so I removed.

` build: {
    html: {
      minify: {
        minifyCSS: true,
        minifyJS: true,
      }
    },
}`

_No response_

**Comment by danielroe** [comment]
Would you explain a bit more about what isn't working?

When I build your project, I get something like this:

```css
--fa-font-regular: normal 400 1em/1 "Font Awesome 6 Regular";--fa-font-light: normal 300 1em/1 "Font Awesome 6 Light";--fa-font-thin: normal 100 1em/1 "Font Awesome 6 Thin";--fa-font-duotone: normal 900 1em/1 "Font Awesome 6 Duotone";--fa-font-brands: normal 400 1em/1 "Font Awesome 6 Brands"}svg:not(:root).svg-inline--fa,svg:not(:host).svg-inline--fa{overflow:visible;box-sizing:content-box}.svg-inline--fa{display:var(--fa-display, inline-block);height:1em;overflow:visible;vertical-align:-.125em}.svg-inline--fa.fa-2xs{vertical-align:.1em}.svg-inline--fa.fa-xs{vertical-align:0em}.svg-inline--fa.fa-sm{vertical-align:-.07143em}.svg-inline--fa.fa-lg{vertical-align:-.2em}.svg-inline--fa.fa-xl{vertical-align:-.25em}.svg-inline--fa.fa-2xl{vertical-align:-.3125em}.svg-inline--fa.fa-pull-left{margin-right:var(--fa-pull-margin, .3em);
```
