### ISSUE TITLE
Problem loading font from assets/css

### ISSUE THREAD

**Issue by jiblett1000** [nuxt/framework#5388]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.3-27579668.27a0084`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `typescript`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jiblett1000/inter-test

### Describe the bug

I am using @font-face from `/assets/css/main.css`, however this creates this error during `yarn build`:

`[vite:build-import-analysis] Cannot destructure property 'line' of 'locate(...)' as it is undefined.`

This was previously working and this error appeared using the edge release within the past couple of weeks.

**Comment by codeflorist** [comment]
here is some more info regarding this error on my side:
----------
the error occurs, if NO format is stated for a font-src:
```css
@font-face {
	font-family: "Open Sans";
	src: url("/fonts/open-sans-v16-latin-300.woff2");
}
```
----------
the error does NOT occur, if the format is stated:
```css
@font-face {
	font-family: "Open Sans";
	src: url("/fonts/open-sans-v16-latin-300.woff2") format("woff2");
}
```
----------
however, the error does ALSO occur WITH the format stated, if the font-face-declaration is inside an imported css file:

`main.css:`
```css
@import '_fonts.css';
```

`_fonts.css:`
```css
@font-face {
	font-family: "Open Sans";
	src: url("/fonts/open-sans-v16-latin-300.woff2") format("woff2");
}
```
