### ISSUE TITLE
Nuxt3 on AWS issue with "404 Cannot find any route matching /."

### ISSUE THREAD

**Issue by gemmadlou** [nuxt/framework#5810]
### Environment

```
Nuxt project info:                                                                                                                                   18:31:56

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.1.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.1`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

- serverless.yml

```yaml
service: 'uposcar-website'
frameworkVersion: '3'
stage: 'prod'

provider:
  name: aws
  runtime: nodejs16.x
  profile: uposcar

functions:
  nuxt:
    handler: .output/server/index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

package:
  exclude:
    - assets/**
    - components/**
    - composables/**
    - layouts/**
    - middleware/**
    - node_modules/**
    - plugins/**
    - server/**
    - stores/**
    - types/**
    - .nuxt/**
  include:
    - .output/**
    - .env
    - public/**

```

- nuxt.config.ts

```ts
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    nitro: {
        preset: 'aws-lambda',
        serveStatic: true
    }
})

```

- Run `npx nitro build`
- Run `sls deploy`
- Visit URL
- It returns 404 :sad

### Describe the bug

I followed the docs on Nuxt3 and Nitro but didn't get beyond this error.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4562670/178155776-05e7edc3-a30b-41c4-8aeb-2abe7c5d2688.png">

### Logs

```shell
AWS Lambda Logs


Test Event Name
Test2

Response
{
  "statusCode": 404,
  "headers": {
    "content-type": "text/html",
    "server-timing": "-;dur=0;desc=\"Generate\""
  },
  "body": "<!DOCTYPE html>\n  <html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <title>404 Cannot find any route matching /.</title>\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@picocss/pico/css/pico.min.css\">\n  </head>\n  <body>\n    <main class=\"container\">\n      <dialog open>\n        <article>\n          <header>\n            <h2>404 Cannot find any route matching /.</h2>\n          </header>\n          <code>\n            Cannot find any route matching /.<br><br>\n            \n\n          </code>\n          <footer>\n            <a href=\"/\" onclick=\"event.preventDefault();history.back();\">Go Back</a>\n          </footer>\n        </article>\n      </dialog>\n    </main>\n  </body>\n</html>\n"
}
```
```
