### ISSUE TITLE
missing .output/public/index.html after upgrading to RC12

### ISSUE THREAD

**Issue by pnzz7** [nuxt/framework#8648]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `buildModules`, `build`, `css`, `head`, `pwa`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.5`, `@vueuse/nuxt@9.4.0`, `@kevinmarrec/nuxt-pwa@0.8.0`
- Build Modules:    `@pinia/nuxt@0.4.3`

### Reproduction

Currently I am building my nuxt3 application without SSR (via setting `ssr: false` in `nuxt.config.ts`). 
Up until the upgrade from nuxt3 RC11 to RC12 there was an index.html file located in .output/public after building the application using `nuxt build` and I was able to deploy the generated SPA Application via AWS Amplify as example using the following config:

```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /.output/public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Describe the bug

after building locally i noticed that the file .output/public/index.html was missing after upgrading from RC11 to RC12. Now with  the index.html file missing, Its is not possible anymore to host a SPA without prerendered routes. 

Please correct me if I missunderstood something there ✌️.
