### ISSUE TITLE
Nuxt 3 + Docker in Production mode - fetch on SS throw error: `Error: request to ..., reason: socket hang up ()`

### ISSUE THREAD

**Issue by iWatchYouFromAfar** [nuxt/framework#9911]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.1-rc.0-27863365.da6fa9a`
- Nitro Version:    `2.0.0-27860563.409fe2b`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `app`, `vite`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Unfortunately it is difficult for me to provide a link for a full reproduction, but I will provide all the necessary source data.

### Describe the bug

[In my past search, I found out that Nuxt 3 is not yet compatible with Node.js version 18 in production mode.](https://github.com/nuxt/framework/issues/9885) I downgraded the Node.js version to 16 and got a new error:

```
Error: request to http://app_production_backend:3001/api/v1/foo/bar failed, reason: socket hang up ()
```

Where `app_production_backend` - is my backend docker service (container name).

I tested my api with:

* Browser;
* Postman
* Curl;
* Vue SPA;
* Nuxt 3 dev mode;

Everything is working fine but in Nuxt 3 production mode, when i try to fetch my API, i meet with this error...

As you can see, i am on the edge channel. But on stable build i get the same error.

Am i doing something wrong?

### Additional context
My production docker-compose yml file:

```
version: '3.7'

volumes:
  production_mongodb_data:

services:
  nginx_container:
    container_name: app_production_nginx
    image: app_production_nginx:latest
    restart: unless-stopped
    build:
      context: ./production/nginx
    links:
      - backend_container
      - frontend_container
    ports:
      - "80:80"
      - "443:443"
      - "8089:8089"
    volumes:
      - ../frontend/:/usr/share/nginx/html/mysite.com/frontend
  backend_container:
    container_name: app_production_backend
    image: app_production_backend:latest
    build:
      context: ./production/backend
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ../backend:/app/backend
    ports:
      - "3001:3001"
      - "9229:9229"
  frontend_container:
    container_name: app_production_frontend
    image: app_production_frontend:latest
    build:
      context: ./production/frontend
    volumes:
      - ../frontend:/app/frontend
    ports:
      - "3050:3050"
    restart: always
    command: "npm run preview"
```

My NGINX config:

```
upstream backend {
    server backend_container:3001;
}

upstream frontend {
    server frontend_container:3050;
}

server {
    listen 80;
    server_name mysite.com;

    location /.well-known/acme-challenge/ {
    	root /var/www/certbot;
    }

    location / {
      	#...
    }

}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2 ipv6only=on;
    server_name mysite.com;

    # SSL certs here

   location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://frontend;
        proxy_ssl_session_reuse off;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_redirect off;
    }

    location /api {
        proxy_pass https://backend;
    }
}
```

My Frontend Dockerfile:

```
FROM node:16-alpine

WORKDIR /app/frontend

EXPOSE 3050
```
